### PR TITLE
Fix producturi in session

### LINKED ISSUE #1170: OPC UA Non-Compliance: Endpoint description information returned by node-opcua server does not match.
NODE-OPCUA stack version : 2.72.2
NODEJS version : v16.15.1

Current Behavior:
 
Endpoint description information returned by node-opcua server in the GetEndPoint Response does not match with the Endpoint description information returned in the Create session response.
Snapshot of wireshark capture GetEndPoint response where the Product URI is returned
image

However in the below CreateSession response wireshark capture snapshot Product URI is empty

image

**Expected behavior**
As per the OPC UA compliance spec, endpoint description returned in the GetEndpointResponse and in the CreateSessionResponse by OPC UA server should exactly match .

Test case:
<html>
<body>

Err-023 | CTT | CreateSession | productUris contained in the returned SoftwareCertificates do not match the productUris in the EndpointDescription used by the Client to connect to the Server. |   | Client closes session calling CloseSession.Client logs and/or display an error to the end user.
-- | -- | -- | -- | -- | --

</body>
</html>

- ( ) my request is related to node-opcua acting as an OPCUA SERVER

### PR DESCRIPTION
**Pull request by JeanArhancet**
Hi,

This is my first MR for this project :) 

Fix #1170

### CODE REVIEW

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+        let endpoints = server._get_endpoints();
+        endpointUrl = endpoints[0].endpointUrl;
+
+
+    });
+    after(function(done) {
+        server.shutdown(done);
+    });
+
+    it("should productURI have the same value", (done) => {
```
Comment (erossignon) [inline packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts]: Please favor new style with async/await instead of callback ... code will be easier to read.

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+
+    const port = 1170;
+    let server = null;
+    let endpointUrl = "";
+
+
+    before(async () => {
+
+
+        server = new opcua.OPCUAServer({
```
Comment (erossignon) [inline packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts:14]: I would provide an explicit productUri in the OPCServer constructor, to make sure we verify against this one and not against the default value.

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+const opcua = require("node-opcua");
+const OPCUAClient = opcua.OPCUAClient;
+const UserTokenPolicy = opcua.UserTokenPolicy;
+const { perform_operation_on_client_session } = require("../../test_helpers/perform_operation_on_client_session");
+// require("node-opcua-service-session").UserNameIdentityToken;
+
+const describe = require("node-opcua-leak-detector").describeWithLeakDetector;
+describe("Testing bug #1170", function() {
+
+    const port = 1170;
```
Comment (erossignon) [inline packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts:10]: Please make sure that port is not used anywhere else in other unit test ... We run unit tests in parallel and all severs must have a different port.

File: packages/node-opcua-server/source/opcua_server.ts [hunk 4]
```diff
@@ -262,9 +262,9 @@ async function _attempt_to_close_some_old_unactivated_session(server: OPCUAServe
 
 function getRequiredEndpointInfo(endpoint: EndpointDescription) {
     assert(endpoint instanceof EndpointDescription);
-    // It is recommended that Servers only include the server.applicationUri,  endpointUrl, securityMode,
-    // securityPolicyUri, userIdentityTokens, transportProfileUri and securityLevel with all
-    // other parameters set to null. Only the recommended parameters shall be verified by
+    // It is recommended that Servers only include the server.applicationUri, server.applicationType, server.applicationName,
```
Comment (erossignon) [inline packages/node-opcua-server/source/opcua_server.ts]: This sentences come from the OPCA spec ( probably v102). 
Now that the spec are available online we could add this link to the comment for cross reference : https://reference.opcfoundation.org/v104/Core/docs/Part4/5.6.2/

> List of Endpoints that the Server supports.
The Server shall return a set of EndpointDescriptions available for the serverUri specified in the request. The EndpointDescription type is defined in [7.10](https://reference.opcfoundation.org/v104/Core/docs/Part4/7.10). The Client shall verify this list with the list from a DiscoveryEndpoint if it used a DiscoveryEndpoint to fetch the EndpointDescriptions.
It is recommended that Servers only include the server.applicationUri, endpointUrl, securityMode, securityPolicyUri, userIdentityTokens, transportProfileUri and securityLevel with all other parameters set to null. Only the recommended parameters shall be verified by the client.


https://reference.opcfoundation.org/v105/Core/docs/Part4/5.6.2/
>List of Endpoints that the Server supports.  
> The Server shall return a set of EndpointDescriptions available for the serverUri specified in the request. All Endpoints are returned if the serverUri is null or empty. The EndpointDescription type is defined in [7.14](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.14). The Client shall verify this list with the list from a DiscoveryEndpoint if it used a DiscoveryEndpoint to fetch the EndpointDescriptions.
It is recommended that Servers only include the server.applicationUri, endpointUrl, securityMode, securityPolicyUri, userIdentityTokens, transportProfileUri and securityLevel with all other parameters set to null or empty. Only the recommended parameters shall be verified by the Client.

**Review by erossignon — CHANGES_REQUESTED** [review]

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts (hunk 3 above)
Comment (JeanArhancet) [reply packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts:10]: This port is not used by other tests

File: packages/node-opcua-server/source/opcua_server.ts (hunk 4 above)
Comment (JeanArhancet) [reply packages/node-opcua-server/source/opcua_server.ts]: Done @erossignon , What do you think?

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts (hunk 2 above)
Comment (JeanArhancet) [reply packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts:14]: I added the parameter

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts (hunk 1 above)
Comment (JeanArhancet) [reply packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts]: Thanks, I just changed

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+                productUri: "Mini NodeOPCUA-Server"
+            }
+        });
+
+        await server.start();
+
+        let endpoints = server._get_endpoints();
+        endpointUrl = endpoints[0].endpointUrl;
+    });
+    after(function (done) {
```
Comment (erossignon) [inline packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts]: I suggest this for consistency:
```
after(async ()=>{
   await server.shutdown();
});
```

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+        server.shutdown(done);
+    });
+
+    beforeEach(async () => {
```
Comment (erossignon) [inline packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts]: As we have only one test, there is no need for this beforeEach/afterEach block, we could also eliminate the variables at the describe scope

````javascript
it("server createSession should expose endpoints with correct productURI ", async()=> {
   const client = OPCUAClient.create({});
    const serverEndpoints = await client.withSessionAsync(async (session)=>{
            return session.serverEndpoints;
    });
    serverEndpoints[0].server.productUri).should.eql("Mini NodeOPCUA-Server");
}};

````

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+        server = new opcua.OPCUAServer({
+            port,
+            serverInfo: {
+                productUri: "Mini NodeOPCUA-Server"
+            }
+        });
+
+        await server.start();
+
+        let endpoints = server._get_endpoints();
```
Comment (erossignon) [inline packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts]: let use the public API,
````
server.getEndpointUri();
```

**Review by erossignon — CHANGES_REQUESTED** [review]

File: packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts (hunk 6 above)
Comment (JeanArhancet) [reply packages/node-opcua-end2end-test/test/end_to_end/test_e2e_1170.ts]: You're right, I've changed
